### ISSUE TITLE
[BUG] Unexpected EOF error when i open the terminal

### ISSUE THREAD

**Issue by nir1300** [WaRtr0/francinette-image#3]
Hi! I downloaded francinette image and i worked fine up until today, when i tried opening the terminal and (without even running francinette) i got an error every second. it says "Loading the docker container... Unexpected EOF"
Are the some lines I have to add to my zshrc file to prevent this from happening?
Best wishes and thanks for creating such a useful tool!
Nina

**Comment by WaRtr0** [comment]
Hey, hi there!! 👋👋

Thank you for your message and sorry for the issue you're encountering.

This error usually happens when the `francinette.tar` file located in `~/francinette-image` is either corrupted or missing. This can be due to bugs during installation or if the disk is full.

I suggest the following steps to resolve the problem:

1. **Check disk space:**
   - Make sure your disk isn’t full, as insufficient space can prevent the proper installation of files.

2. **Uninstall francinette-image:**
   - Copy and paste this command in your terminal to properly uninstall francinette-image:

     ```bash
     bash -c "$(curl -fsSL https://raw.githubusercontent.com/WaRtr0/francinette-image/master/uninstall.sh)"
     ```

   - Ensure that the `~/francinette-image` folder no longer exists after this operation.

3. **Reinstall francinette-image:**
   - Copy and paste this command to reinstall francinette-image:

     ```bash
     bash -c "$(curl -fsSL https://raw.githubusercontent.com/WaRtr0/francinette-image/master/install.sh)"
     ```

This should fix it! If the problem persists or something goes wrong during reinstallation, feel free to let me know and tell me at which step the issue occurs.

Thx 🙏

Max
